### ISSUE TITLE
Change OT Rules?

### ISSUE THREAD

**Issue by jonesguy14** [jonesguy14/footballcoach#16]
Some users have requested changing the OT rules to be more like college.

So instead of a full new quarter, some sort of score-then you score type of thing.

**Comment by destilla** [comment]
Work is looking a little crazy between now and Friday, but I should have some free time randomly between now and the weekend to do some work on this. I

I have an idea of how we can add this, and have possession restart for the first team to go on offense (and add a change of possession after halftime).

My thinking on the end result is something like this:

- Because home team gets the ball to start the game, after the last play of the 2ndQ, away team starts on their own 25 (kickoff touchback starting position in NCAA), with the ball and the clock reset to 15:00 left in the 3rdQ.

- For OT, because going second is generally seen as a good thing, away team goes first in OT1 so that home team gets the benefit of knowing what they need. Just like real life, if the game reaches OT2, home team will go first and away team will go second. They'll alternate after that.

- To actually make going second a benefit, add a variable to check if it's the second half of an overtime period (aka are you going second), and change the condition you wrote to go for it on 4th down under a certain amount of time left in the game if you need a TD to include also doing that in the second half of an OT. That way the second team gets all 4 downs to try and make something happen, and also doesn't try to kick a FG while down by 7.  

- Update kickXP to check if it's 3rd OT or higher and force a team to go for 2 (because NCAA OT rules say you can't kick the XP starting in 3rd OT)


----




Thoughts? Any end results you would change?

**Comment by jonesguy14** [comment]
Yes all those ideas sound good. I actually started to make OT rules last week but stopped midway. I basically did exactly what you talked about here (away team starts with ball, have variable that tracks if it is in top half or bottom half of OT, change code elsewhere so that if a TD is scored in OT, kickOff doesn't happen but the other team may get the ball) but it was buggy and wasn't working how I wanted. If you want I can send you my modified Game.java with my changes, but not sure if that would help or hurt.

**Comment by destilla** [comment]
Generally speaking I've had good results using your code as a base to create something, so I think it would definitely help. Worst case scenario, I look it over and just start fresh. Best case scenario, I avoid pitfalls you've already discovered or find a cleaner way to do something I had in mind.

**Comment by jonesguy14** [comment]
Ok, when I'm back my desktop later tonight I'll post it and explain more about what I tried.

**Comment by destilla** [comment]
Alright, sounds good. I have dinner plans for tonight and a meeting at work tomorrow from the morning til after lunch probably, but then after that I should have some time to dedicate to this. I'll probably end up checking it in the morning before the meetings.

**Comment by jonesguy14** [comment]
Yeah man no worries, don't feel like it's super urgent or anything, just whenever you have time and if you want to.

**Comment by jonesguy14** [comment]
Just posted it as Game_OT_rules_test.java, not sure if there was a better way but whatever I'll remove it later.

Basically:

- Has playingOT variable, true when playing OT
- Has flipOT boolean variable, which is false when its the top half of OT, true when its the bottom half
- have this in the playGame() function:

`
if (gameTime <= 0 && homeScore == awayScore) {
                    playingOT = true;
                    gamePoss = false;
                    gameYardLine = 70;
                    numOT++;
                    gameTime = -1;
                    gameDown = 1;
                    runPlay( awayTeam, homeTeam );
                }
`
- Then in runPlay, I have this loop which deals with logic of when to go for FG vs TD:
`
if (playingOT) {
            // OT RULES BAYBEE
            while (playingOT) {

                if (gamePoss) {
                    offense = homeTeam;
                    defense = awayTeam;
                } else {
                    offense = awayTeam;
                    defense = homeTeam;
                }

                if (flipOT) {
                    // Second half of OT, live or die
                    if (gameDown == 4) {
                        gameEventLog += getEventPrefix() + offense.abbr + " has the ball and it is 4th down in bottom of OT.";
                        // decide to go for FG or TD
                        if ((gamePoss && (awayScore - homeScore) <= 3) || (!gamePoss && (homeScore - awayScore) <= 3)) {
                            fieldGoalAtt(offense, defense);
                        } else {
                            passingPlay(offense, defense);
                        }
                    } else if ((gameDown == 3 && gameYardsNeed > 4) || ((gameDown == 1 || gameDown == 2) && (preferPass >= preferRush))) {
                        // pass play
                        passingPlay(offense, defense);
                    } else {
                        //run play
                        rushingPlay(offense, defense);
                    }
                } else {
                    // the first team of the two, will settle for FG if 4th down
                    if (gameDown == 4) {
                        gameEventLog += getEventPrefix() + offense.abbr + " has the ball, 4th down in top of OT, go for FG.";
                        fieldGoalAtt(offense, defense);
                    } else if ((gameDown == 3 && gameYardsNeed > 4) || ((gameDown == 1 || gameDown == 2) && (preferPass >= preferRush))) {
                        // pass play
                        passingPlay(offense, defense);
                    } else {
                        //run play
                        rushingPlay(offense, defense);
                    }
                }
            }
        }
`

- Then I have a resetOT function, which is called whenever a TD/FG is scored, or when a turnover occurs. It basically checks to see what half of OT it is on. If there is still a half to be played, it gives the ball to the other team. If its the bottom of OT, it resets OT only if the scores are tied. If not, it sets playingOT to false and would (hopefully) exit the while loop from runPlay

So that's what I have for now. Let me know if you have any questions. Again, no rush and its only if you feel like taking on the challenge.

**Comment by destilla** [comment]
Oh, I definitely want and I think I'm up to the challenge, and in retrospect, I'm not sure why I felt the need to walk through my schedule, lol. I think I mostly wanted to communicate that I am interesting in trying to tackle this but that I'm going to be a bit busy for a day or two.

I'm poking around the code you uploaded and you definitely have some stuff I want to use; especially the way you handled the change to OT in getEventPrefix(), I really liked that.

I did have a few questions:

`if (gameTime < 100) homeScore = awayScore;`

That line if code is in the while loop for playGame(), right after the lines for the two different runPlay()s. If I understand java correctly (which is a tremendous leap of faith), you basically set that line there to force a game into OT and to test that it works?

If not, what's it do?

--

In the runPlay() logic I saw that for the top half of OT, the offense kicks a FG on 4th down. How do you feel about having that be stategy dependent? 

An example might be:
Conservative always kicks the FG
No preference will go for it with 3 or less yards to go AND it's goal to go (aka 4th and goal from the 97 or closer), or go for it on 4th and 1.  
Aggressive either always goes for it or does something like kick the FG any time it's 5 or more yards to go, or for goal to go situations, kick the FG any time it's more than 7 yards.

I'm not married to any of those specific routes, just spitballing ideas so you see what I mean and to get an opinion.

--

Finally, I think I understand how resetForOT() works, basically just sets possession, yardline, down, etc and then continues the while loop in playGame, but you had mentioned that you ran into some bugs with the existing code. At a quick glance this looks pretty solid; do you remember anything in particular that you found while doing testing? Just so I can be aware of things to look out.



Thanks for the sample code!

**Comment by destilla** [comment]
Oh one other question -- Where can I find r.achijones.footballcoach? Or at least how can I add a new menu item (though I realize the second question is probably way more complex) All of the menu items reference get r.id.action_for_menu_thing but I can't find an R, other than the one I think Android Studio is creating, and that's blank.

I was hoping to try something like creating a log with each runPlay that would save them to a string and then check them out in a menu item, similar to what you've got with the news stories, for testing purposes. That way I can look at what is happening with the plays and if it's behaving how I would expect (and also because I found an interesting bug last night that I'll post when I'm not late for a meeting). I tried to do the menu myself but I can't figure out what I'm doing wrong (or not doing at all).

**Comment by jonesguy14** [comment]
Yeah the line where it sets the scores equal is just for testing, so you won't have to wait for an OT game to be played organically (as in all games will go to OT).

Yeah attaching strategies to whether a team should go for it on 4th down is definitely something that should be added, but I wouldn't worry about that until the regular OT rules are in place. I like your ideas though.

Not sure exactly what bugs I had, I just know that I was getting impossible scores (like a team would win by 14 even though it went to OT) and so I just ditched it to work on something else for the 1.2 release.

For the R thing, if you are talking about the menu in the top right, you need to look at menu_main.xml to add menu items. That's where all the action_blahblah are defined. But if you are just debugging for the games, I would just add debug stuff to the gameEventLog so you can see what is happening for a particular game.

**Comment by destilla** [comment]
So, I don't have the play selection logic worked out (or even started) yet, but OT rules are in place and behaving as they should. I verified this by very powerfully failing to create an alert dialog that would let me know if any OT scores were greater than 8, and ran a few seasons.

Then, to be sure my alert dialog worked, I set it to popup any time a game ended with a difference in score of more than 7. Week one had a game settled by a difference of 8 points and the app promptly crashed. But still, the app _didn't_ crash when I was checking to see if games were ending with a bigger difference than 8, so everything seems copasetic at the moment.


How deep do you want the logic for runPlay to be in accounting for OT play calling for the first pass of college overtime rules? The games seem to flow pretty normally with the existing play calling logic: When they're far, they pass it, when they're near, the run it, when it's 4th down, they kick the fg. I can insert an extra line to address having to go for it in the bottom frame of OT if you're down by more than 3 and then the very basic functionality exists. 

From there it can be expanded on (and if you're not opposed I would like to go deeper than just playing OT like any other time in the game), but I don't know your level of wanting to just have OT in vs have OT in and deeper logic.

Here's a screenshot of OT in action; I probably 50/50 used your code/new code for this.

![image](https://cloud.githubusercontent.com/assets/11052658/14040605/08780778-f226-11e5-82d1-84097ce97e29.png)

![image](https://cloud.githubusercontent.com/assets/11052658/14040624/2b1c723c-f226-11e5-94dc-f190d4819762.png)

![image](https://cloud.githubusercontent.com/assets/11052658/14040631/39f1f61a-f226-11e5-906f-876e3e6dc3f7.png)

**Comment by destilla** [comment]
Also, funny story:

I originally forgot to update the logic to not endlessly kick fgs in ot (last second fg attempt kicked in because time is always < 30 and I never set !playingOT)

So you ended up with stuff like this:

![image](https://cloud.githubusercontent.com/assets/11052658/14040784/ebd02bda-f227-11e5-94ca-2971d2bbb2f4.png)


The worst I saw was 16OT. Alabama and Kentucky couldn't get ahead of each other for 16 frames. It was like watching an NHL shootout with high school shooters and professional goalies.

**Comment by jonesguy14** [comment]
Looks good! For runPlay, I think you are right that it flows pretty well as-is, but I would want logic for the bottom half team to go for it if they are down by more than 3. From there we can expand it later (and play calling in general) to include logic that comes from what strategy the team is running.

Just released an update yesterday with some UI changes, but maybe early next week we can put the OT rules out! Great work!

**Comment by destilla** [comment]
Awesome! Just created the pull request for OT! 

Re: going for it on 4th down when you need a TD -- You actually already had logic that took care of that. The same logic that has a team go for it with less than 5 minutes to play if they need the TD also applies in OT since OT is always gameTime < 300 (because it's negatives).

Thanks for the praise/feedback! It's funny because a few times I would write something, say "well let me see how jonesguy did it", check your code, and it would be the exact same (sometimes down to the formatting and spacing). So thank you for providing me with a great base.

**Comment by jonesguy14** [comment]
Fixed with commit e5cd0300f27fa0d7c6fdabb49204fc32876854c8
